version: '3'
services:
  app1:
    build: .
    expose:
      - 8000

  app2:
    build: .
    expose:
      - 8000

  nginx:
    build: ./nginx
    ports:
    - "8000:80"
    depends_on:
      - app1
      - app2