version: '3'
services:
  app1:
    build: .
    expose:
      - 8000

  app2:
    build: .
    expose:
      - 8000

  nginx:
    build: .
    ports:
    - "8080:80"
    depends_on:
      - app1
      - app2